services:
  - type: web
    name: rate-limiter
    runtime: node
    repo: https://github.com/abhishekkalme/Redis-Based-API-Rate-Limiter
    plan: free
    buildCommand: npm run build
    startCommand: node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDIS_TLS
        value: "true"
      - key: REDIS_URL
        sync: false
      - key: RATE_LIMIT_STRATEGY
        value: token-bucket
      - key: LOG_LEVEL
        value: info